# Generated by Django 6.0 on 2025-12-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('INSPECTION', 'Inspection'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('cleaning_type', models.CharField(choices=[('STANDARD', 'Standard'), ('DEEP', 'Deep'), ('CHECKOUT', 'Checkout')], default='STANDARD', max_length=20)),
                ('guest_status', models.CharField(choices=[('GUEST_OUT', 'Guest Out'), ('GUEST_IN_ROOM', 'Guest in Room'), ('NO_GUEST', 'No Guest'), ('DND', 'Do Not Disturb')], default='NO_GUEST', max_length=20)),
                ('assigned_group', models.CharField(blank=True, help_text="e.g. 'Group 1'", max_length=50, null=True)),
                ('priority', models.BooleanField(default=False)),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
