# Generated by Django 6.0 on 2025-12-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_setup',
            field=models.CharField(default='1 King', help_text="e.g. '1 King, 2 Singles'", max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='bedroom_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='extras_text',
            field=models.CharField(blank=True, help_text="Comma-separated extras (e.g. 'Crib, Towels')", max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='cleaning_type',
            field=models.CharField(choices=[('DEPARTURE', 'Departure'), ('STAYOVER', 'Stayover'), ('WEEKLY', 'Weekly'), ('DAYUSE', 'Day Use'), ('HOLDOVER', 'Holdover'), ('PREARRIVAL', 'Pre-Arrival'), ('RUBBISH', 'Rubbish')], default='DEPARTURE', max_length=20),
        ),
    ]
