# Generated by Django 6.0 on 2025-12-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0002_room_bed_setup_room_bedroom_count_room_extras_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='current_guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='next_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='next_guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
