# Generated by Django 6.0 on 2025-12-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0003_room_check_in_date_room_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='maintenance_reason',
            field=models.TextField(blank=True, help_text='Reason for maintenance status', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('INSPECTION', 'Inspection'), ('COMPLETED', 'Completed'), ('MAINTENANCE', 'Maintenance')], default='PENDING', max_length=20),
        ),
    ]
