# Generated by Django 6.0 on 2025-12-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0005_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='housekeeping.room'),
        ),
    ]
