# Generated by Django 6.0 on 2025-12-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0006_alter_incident_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('LINEN', 'Linen'), ('TOILETRIES', 'Toiletries'), ('CLEANING', 'Cleaning Supplies'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='target_role',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('RECEPTION', 'Reception'), ('SUPERVISOR', 'Supervisor'), ('HOUSEMAN', 'Houseman')], default='MAINTENANCE', max_length=20),
        ),
    ]
