# Generated by Django 6.0 on 2025-12-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0007_inventoryitem_alter_incident_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='min_stock',
            field=models.IntegerField(default=10),
        ),
    ]
