# Generated by Django 6.0 on 2025-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0008_inventoryitem_min_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('estimated_minutes', models.IntegerField(default=30)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='cleaning_type',
            field=models.CharField(default='DEPARTURE', max_length=50),
        ),
    ]
