# Generated by Django 6.0 on 2026-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0009_cleaningtypedefinition_alter_room_cleaning_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('target_duration_minutes', models.IntegerField(default=0)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERTIME', 'Overtime')], default='IN_PROGRESS', max_length=20)),
            ],
        ),
    ]
