# Generated by Django 6.0 on 2026-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0010_cleaningsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cleaning_type',
            field=models.CharField(choices=[('DEPARTURE', 'Departure'), ('PREARRIVAL', 'Pre-arrival'), ('WEEKLY', 'Weekly'), ('HOLDOVER', 'Holdover'), ('RUBBISH', 'Rubbish'), ('DAYUSE', 'Day Use')], default='DEPARTURE', max_length=50),
        ),
    ]
