# Generated by Django 6.0 on 2026-01-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0013_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='first_time_cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_guest_waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_dnd_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
