# Generated by Django 6.0 on 2026-01-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0015_room_last_inspection_report_announcement_lostitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('GUEST_REQ', 'Guest Request'), ('SUPPLY', 'Supply Request'), ('PREVENTIVE', 'Preventive Maintenance')], default='MAINTENANCE', max_length=20),
        ),
    ]
