# Generated by Django 6.0 on 2026-01-04 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0016_incident_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GOOD', 'Good'), ('REPAIR', 'Repair Needed'), ('BROKEN', 'Broken')], default='GOOD', max_length=20)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='housekeeping.room')),
            ],
        ),
    ]
