# Generated by Django 6.0 on 2026-01-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0019_room_assigned_cleaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='supplies_used',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
