# Generated by Django 6.0 on 2026-01-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0020_room_supplies_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffavailability',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Override end time for Partial availability', null=True),
        ),
        migrations.AddField(
            model_name='staffavailability',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Override start time for Partial availability', null=True),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('VACATION', 'Vacation'), ('OFF', 'Off Day'), ('PARTIAL', 'Partial Day')], default='AVAILABLE', max_length=20),
        ),
    ]
