# Generated by Django 6.0 on 2026-01-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0021_staffavailability_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_details',
            field=models.JSONField(blank=True, default=dict, help_text='JSON structure: {reservation_number, guests, departure_date, etc}', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True, help_text='Housekeeping notes for this room', null=True),
        ),
    ]
