# Generated by Django 6.0 on 2026-01-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0022_room_guest_details_room_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleaning_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
