# Generated by Django 6.0 on 2026-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0023_room_cleaning_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_houseman_completed',
            field=models.BooleanField(default=False),
        ),
    ]
