# Generated by Django 6.0 on 2026-01-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0024_room_is_houseman_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='assigned_group',
            field=models.CharField(blank=True, help_text="e.g. 'Group 1' or 'Lobby Team'", max_length=50, null=True),
        ),
    ]
