# Generated by Django 6.0 on 2026-01-21 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0025_alter_room_assigned_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('GUEST_REQ', 'Guest Request'), ('SUPPLY', 'Supply Request'), ('PREVENTIVE', 'Preventive Maintenance'), ('TASK', 'General Task')], default='MAINTENANCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='target_role',
            field=models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('RECEPTION', 'Reception'), ('SUPERVISOR', 'Supervisor'), ('HOUSEMAN', 'Houseman'), ('CLEANER', 'Cleaner')], default='MAINTENANCE', max_length=20),
        ),
    ]
