# Generated by Django 6.0 on 2026-01-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0026_incident_assigned_to_alter_incident_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_cleaning_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
