# Generated by Django 6.0 on 2026-02-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0027_room_last_cleaning_duration_room_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningsession',
            name='break_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
