# Generated by Django 6.0 on 2025-12-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('CLEANER', 'Cleaner'), ('MAINTENANCE', 'Maintenance'), ('RECEPTION', 'Reception'), ('HOUSEMAN', 'Houseman'), ('ADMIN', 'Administrator')], default='CLEANER', max_length=20),
        ),
    ]
