# Generated by Django 6.0 on 2026-01-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group_id',
            field=models.CharField(blank=True, choices=[('Group 1', 'Group 1'), ('Group 2', 'Group 2'), ('Group 3', 'Group 3'), ('Group 4', 'Group 4'), ('Group 5', 'Group 5'), ('Group 6', 'Group 6'), ('Group 7', 'Group 7'), ('Group 8', 'Group 8'), ('Group 9', 'Group 9'), ('Group 10', 'Group 10')], help_text="e.g. 'Group 1'", max_length=50, null=True),
        ),
    ]
