# Generated by Django 6.0 on 2026-01-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.TextField(blank=True, help_text='URL to avatar image', null=True),
        ),
    ]
